# we want to make sure it is run on trusty where sudo is provided for postgres
dist: trusty
language: python
sudo: required
matrix:
  include:
    - name: Python 3.6, Dummy DB
      python: 3.6
      env: DATABASE=DUMMY
    - name: Python 3.6, PG 9.6
      python: 3.6
      env: DATABASE=postgres
      addons:
        postgresql: 9.6
    - name: Python 3.6, PG 10.6
      python: 3.6
      env: DATABASE=postgres PGPORT=5433
      addons:
        postgresql: "10"
        apt:
          packages:
          - postgresql-10
          - postgresql-client-10
    - name: Python 3.6, Cockroachdb
      python: 3.6
      env: DATABASE=cockroachdb
    - name: Python 3.7, Dummy DB
      python: "3.7"
      env: DATABASE=DUMMY
    - name: Python 3.7, PG 9.6
      python: "3.7"
      env: DATABASE=postgres
      addons:
        postgresql: 9.6
    - name: Python 3.7, PG 10.6
      python: "3.7"
      env: DATABASE=postgres PGPORT=5433
      addons:
        postgresql: "10"
        apt:
          packages:
          - postgresql-10
          - postgresql-client-10
    - name: Python 3.7, Cockroachdb
      python: "3.7"
      env: DATABASE=cockroachdb

services:
  - postgresql
  - docker
before_script:
  - psql -c 'create database guillotina;' -U postgres || true

cache:
  directories:
    - eggs
install:
  - pip install Cython==0.27.3
  - pip install -r requirements.txt
  - pip install -e .[test]
  - pip install pyflakes==1.6.0 pycodestyle==2.3.1 flake8==3.5.0 codecov mypy
  - sleep 5
script:
  - flake8 guillotina --config=setup.cfg
  - mypy guillotina/
  - pytest -s --cov=guillotina -s --tb=native -v --cov-report term-missing --cov-append guillotina
after_success:
  - codecov

deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true
