# we want to make sure it is run on trusty where sudo is provided for postgres
dist: trusty
language: python
python: 3.6-dev
sudo: required

services:
  - postgresql
# make sure we're on the latest version of postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database guillotina;' -U postgres

cache:
  directories:
    - eggs
install:
  - pip install -r requirements.txt
  - pip install -e .[test]
  - pip install flake8
  - sleep 5
script:
  - pytest -s --cov=guillotina -s --tb=native -v --cov-report term-missing guillotina
  - USE_COCKROACH=true pytest -s --tb=native -v guillotina
  - flake8 guillotina --config=setup.cfg
after_success:
  - pip install coveralls
  - coveralls
