---
databases:
- db:
    storage: postgresql
    transaction_strategy: resolve_readcommitted
    dsn:
      scheme: postgres
      dbname: guillotina
      user: postgres
      host: localhost
      password: ''
      port: 5432
    pool_size: 40
    read_only: false
host: 0.0.0.0
port: 8080
root_user:
  password: root
cors:
  allow_origin:
  - "*"
  allow_methods:
  - GET
  - POST
  - DELETE
  - HEAD
  - PATCH
  allow_headers:
  - "*"
  expose_headers:
  - "*"
  allow_credentials: true
  max_age: 3660
utilities: []
partitioner: guillotina.db.partition.ContainerPartitioner
