postgresql:
  image: postgres:10.1
  ports:
    - "127.0.0.1:5432:5432"
  environment:
    POSTGRES_DB: "guillotina"
    POSTGRES_USER: "postgres"
  volumes:
    - ./postgres-data:/var/lib/postgresql/data
