replicaCount: 2

name: guillotina

image:
  repository: guillotina/guillotina
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

arguments: [--override="root_user.password=foobar", --override="debug=false" ]