replicaCount: 2

name: guillotina

image:
  repository: guillotina/guillotina
  tag: latest
  pullPolicy: IfNotPresent

exposedPort: 32354

serviceType: NodePort

resources: {}

guillotinaPort: 8080

arguments: []
