name: guillotina

on: [push]

jobs:

  # Job to run pre-checks
  pre-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install $(grep "Cython" requirements.txt)
          pip install -r requirements.txt
          pip install -r contrib-requirements.txt
          pip install -e .[test]
          pip install -e .[testdata]

      - name: Run pre-checks
        run: |
          flake8 guillotina --config=setup.cfg
          mypy guillotina/ --ignore-missing-imports
          isort -c -rc guillotina/
          black --check --verbose guillotina

  # Job to run tests
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8]
        database: [DUMMY, postgres, cockroachdb]
        db_schema: [public, custom]

    # Set environment variables
    env:
      DATABASE: ${{ matrix.database }}
      DB_SCHEMA: ${{ matrix.db_schema }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        if: (env.DATABASE == 'public' || env.DB_SCHEMA == 'postgres') == 'true'

      - name: Setup Python
        if: (env.DATABASE == 'public' || env.DB_SCHEMA == 'postgres') == 'true'
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the package
        if: (env.DATABASE == 'public' || env.DB_SCHEMA == 'postgres') == 'true'
        run: |
          pip install $(grep "Cython" requirements.txt)
          pip install -r requirements.txt
          pip install -r contrib-requirements.txt
          pip install -e .[test]
          pip install -e .[testdata]

      - name: Run tests
        if: (env.DATABASE == 'public' || env.DB_SCHEMA == 'postgres') == 'true'
        run: |
          pytest -rfE --reruns 2 --cov=guillotina -s --tb=native -v --cov-report term-missing --cov-append guillotina
